#!/usr/bin/bash
# TODO Validate how env vars work with S6
export HOME=${OLLAMA_HOME:-/config}
export OLLAMA_MODELS=${OLLAMA_MODELS:-/data/ollama}
export OLLAMA_HOST=${OLLAMA_HOST:-0.0.0.0}
if [[ ! -d "${HOME}" ]]; then
  mkdir -p "${HOME}"
fi
if [[ ! -d "${OLLAMA_MODELS}" ]]; then
  mkdir -p "${OLLAMA_MODELS}"
fi
/command/s6-notifyoncheck /app/ollama serve
