version: '3.9'

services:
  litellm-ollama1:
    build:
      dockerfile: Dockerfile
    restart: unless-stopped
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    ports:
      - "8000:8000"
      - "11434:11434"
    volumes:
      - "/srv/data/ollama:/root/.ollama"
