version: '3.9'

services:
  fooocus:
    build:
      dockerfile: Dockerfile
    restart: unless-stopped
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    ports:
      - "81:7865"
    volumes:
      - "/srv/config/fooocus:/config" # Config.txt will be stored here
      - "/srv/config/fooocus/presets:/app/presets"
      - "/srv/data/fooocus/models:/app/models"
      - "/srv/data/fooocus/outputs:/app/outputs"
    environment:
      TZ: "UTC"
      config_path: /config/config.txt
      path_checkpoints: /app/models/Stable-diffusion #/app/models/checkpoints
      path_loras: /app/models/Lora #/app/models/loras
      path_vae_approx: /app/models/VAE-approx #/app/models/vae_approx
    command:
      - --theme
      - dark
      - --preset
      - realistic
      - --always-gpu
    labels:
      - homepage.group=ImageGeneration
      - homepage.name=Fooocus
      - homepage.href=http://<this-host>:81/
