version: '3.9'

x-nvidia: &nvidia
  runtime: nvidia
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities:
              - gpu

services:
  automatic1111:
    build:
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "81:7861"
    volumes:
      - "/srv/config/automatic1111:/config" # Holds any json config files
      - "/srv/data/automatic1111/models:/app/models"
      - "/srv/data/automatic1111/outputs:/app/outputs"
      - "/srv/data/automatic1111/extensions:/app/extensions"
      - "/srv/data/automatic1111/embeddings:/app/embeddings"
      - "/srv/data/automatic1111/log:/app/log"
    environment:
      TZ: "UTC"
    command:
      - --theme
      - dark
      - --api
      - --api-log
      - --listen
      - --enable-insecure-extension-access
    labels:
      - homepage.group=ImageGeneration
      - homepage.name=AUTOMATIC1111
      - homepage.href=http://<this-host>:81/
