#!/usr/bin/bash
# shellcheck shell=bash
while ! nc -z localhost 11434; do
  sleep 0.5s
done
if [[ -n "${OLLAMA_PULL:-}" ]]; then
  echo -n "${OLLAMA_PULL:-}" | xargs -P1 -n1 -d ',' /app/ollama pull
fi
