on:
  push:
    paths:
      - ci-debug/**

jobs:
  debug:
    runs-on: ubuntu-latest
    name: R&D Debug Action
    steps:
      - name: Git checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Debug action
        uses: './ci-debug'
        env:
          foo_string: bar
          foo_array: | 
            bar_one
            bar_two
